add github actions workflow and yaml syntax checks
ARINC-IA/CSMIM pull request #5
Opened 2024-07-25 14:57 UTC by matthias-heinisch

first implementations added here

2024-08-23 16:08 UTC, uwe-salomon commented
Example code for checking the YAML of a type spec:

~~~python
def pytest_generate_tests(metafunc):
    typeFiles = glob.glob('types/*')
    if "typeFile" in metafunc.fixturenames:
        metafunc.parametrize("typeFile", typeFiles)



def test_type_file(typeFile):
    assert re.match(r'types/csmim\.obj\..*\d+\.yaml$', typeFile) is not None
    
    fd = open(typeFile, 'r')
    ty = yaml.safe_load(fd)
    
    assert "id" in ty
    assert isinstance(ty["id"], str)
    assert len(ty["id"]) > 0
    assert re.match(r'^[a-z0-9_\-\.]+$', ty["id"]) is not None  # FIXME: Underscore not allowed?
    assert typeFile == "types/" + ty["id"] + ".yaml"
    
    assert "supertypes" in ty
    for supertype in ty["supertypes"]:
        assert len(glob.glob('types/' + supertype + '.yaml')) == 1
~~~

All but one check for the "id" attribute might be replaced by a schema check.

This example does multiple checks in one function, which we discussed is bad style. But it does the yaml conversion only once, which is desirable. Maybe the `pytest_generate_tests()` function can be extended to parametrize with a tuple that contains the file name and the yaml? Or maybe we can use a test fixture that loads the file once before executing the tests?

2024-08-23 16:11 UTC, uwe-salomon commented
Example code for checking that there is no supertype cycle:

~~~python
class VisitSupertypes:
    def __init__(self, types):
        self.types   = types
        self.visited = set()
    
    def visit(self, ty):
        self.visited.add(ty["id"])
        for supertype in ty["supertypes"]:
            assert not supertype in self.visited
            self.visit(self.types[supertype])



def test_supertype_cycles():
    typeFiles = glob.glob('types/*')
    types     = {}
    
    for typeFile in typeFiles:
        try:
            fd = open(typeFile, 'r')
            ty = yaml.safe_load(fd)
            if typeFile == "types/" + ty["id"] + ".yaml":
                types[ty["id"]] = ty
        except:
            print("ignoring " + typeFile)  # FIXME: Insert placeholder in types dictionary?

    for tyId in types:
        VisitSupertypes(types).visit(types[tyId])
~~~

Again, if more tests are written that need the list of all types parsed into YAML, it would be great to do the expensive parsing (and ignoring errors caught by previous tests) only once.

2024-08-27 12:30 UTC, uwe-salomon commented
The check_cycle() function looks good. I just noticed that it does not search for cycles but for "double supertypes", i.e. any case where a type file appears more than once when iterating through the supertypes. We did not specify in the standard whether that is legal and what it means, if I remember correctly.

In any case, I created a repository that collects test cases for the test suite, in order to verify it better: https://github.com/uwe-salomon/csmim-testsuite. See the `types/csmim.obj.circle.4.yaml` there for such a double-supertype case that is not a circle.

2024-08-27 12:46 UTC, uwe-salomon requested changes
Thanks for your work, especially for finding the schemas for yaml!

2024-08-27 13:39 UTC, matthias-heinisch commented on .github/workflows/csmim_schema.yaml
> +supertypes: list(required=False)
well, I added the check with respect to the security concern in your other comment (regarding glob patterns)

2024-08-28 07:16 UTC, matthias-heinisch commented on .github/workflows/csmim_schema.yaml
> +  enum-values: map(required=False)
conditions in the schema are not supported and discouraged. We could introduce enum-resources and other-resources in the schema, but this gets complex quickly. So I will keep all possible options in the schema and add further tests with pytest to check this.

2024-08-28 07:16 UTC, matthias-heinisch commented on .github/workflows/csmim_schema.yaml
> +  parameters: list(include('attribute'))
conditions in the schema are not supported and discouraged. We could introduce enum-resources and other-resources in the schema, but this gets complex quickly. So I will keep all possible options in the schema and add further tests with pytest to check this.

2024-08-28 07:19 UTC, matthias-heinisch commented on .github/workflows/test-csmim-syntax.py
> +    ty = yaml.safe_load(fd)
you are right, but it is just saving one line... If you want to do it, I support it.

2024-08-28 08:07 UTC, uwe-salomon commented on .github/workflows/csmim_schema.yaml
> +  parameters: list(include('attribute'))
I added such a test.

2024-08-28 08:07 UTC, uwe-salomon commented on .github/workflows/csmim_schema.yaml
> +  enum-values: map(required=False)
I added such a test.

2024-08-28 08:09 UTC, uwe-salomon commented
I also removed the exception handling from the supertypes check to make the coder simpler. If an exception is raised, we can just fail the check with that exception. I tested it with an invalid supertypes spec.

2024-08-28 08:13 UTC, uwe-salomon approved these changes

2024-08-28 10:24 UTC, uwe-salomon commented
Hey Matthias, I completed the "path/" tests and added the conflict tests for resource IDs and paths etc. I think we have a pretty good foundation now. The conflict tests are a bit complex, regrettably. What do you think?

2024-08-28 13:25 UTC, uwe-salomon approved these changes

2024-08-29 09:36 UTC, matthias-heinisch reviewed
looks great! only one tiny comment that I will adapt, then open for review.

2024-08-29 09:36 UTC, matthias-heinisch commented on .github/workflows/test-csmim-syntax.py
> +        assert re.fullmatch("[A-Za-z0-9\\-\\._]+", os.path.basename(pathFile))
```suggestion
        assert re.fullmatch("[A-Za-z0-9\\-._]+", os.path.basename(pathFile))
```

2024-08-29 13:24 UTC, uwe-salomon approved these changes
Good work!

2024-08-29 16:41 UTC, DennisWhetten-Boeing approved these changes
I looked through the code and comments/discussion; I didn't check for efficacy or all functionality yet. From everything I've seen it looks great!

2024-08-30 06:51 UTC, merged